### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by Yaoyu-F** [a-r-j/CPDB#5]
Macbook pro 2021 M1 pro
Ststem: Mac OS 14.3.1 (23D60)
Python 3.8.19
numpy 1.24.3

Error: 
Building wheels for collected packages: cpdb-protein
  Building wheel for cpdb-protein (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for cpdb-protein (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-11.1-arm64-cpython-38
      creating build/lib.macosx-11.1-arm64-cpython-38/cpdb
      copying cpdb/__init__.py -> build/lib.macosx-11.1-arm64-cpython-38/cpdb
      running build_ext
      building 'cpdb.parser' extension
      creating build/temp.macosx-11.1-arm64-cpython-38
      creating build/temp.macosx-11.1-arm64-cpython-38/cpdb
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/opt/homebrew/anaconda3/envs/pytorch/include -arch arm64 -I/opt/homebrew/anaconda3/envs/pytorch/include -arch arm64 -I</opt/homebrew/opt/portaudio>/include/ -I/opt/homebrew/anaconda3/envs/pytorch/include/python3.8 -c cpdb/parser.c -o build/temp.macosx-11.1-arm64-cpython-38/cpdb/parser.o
      cpdb/parser.c:1240:10: fatal error: 'numpy/arrayobject.h' file not found
      #include "numpy/arrayobject.h"
               ^~~~~~~~~~~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]

**Comment by Yaoyu-F** [comment]
The pathway of "numpy/arrayobject.h" is "/opt/homebrew/anaconda3/envs/pytorch/lib/python3.8/site-packages/numpy/core/include/numpy/arrayobject.h".

**Comment by a-r-j** [comment]
Hmm, I just tried a fresh environment on my M1 Pro which worked fine:

```
conda create -n cpdb python=3.8
conda activate cpdb
pip install numpy==1.24.3
pip install cpdb-protein
```

What's the output of `gcc --version`? Mine's `15.0.0`.

**Comment by Yaoyu-F** [comment]
Hmm, I also tried to create a new environment using your code in my MAC. But it still do not work.
But in the remote server, it worked.
```
% gcc --version
Apple clang version 15.0.0 (clang-1500.1.0.2.5)
Target: arm64-apple-darwin23.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by Yaoyu-F** [comment]
Also I update my conda to conda 23.10.0.

**Comment by Yaoyu-F** [comment]
I solved that using a easy way. Just run the command blew before `pip install cpdb-protein`.

```
export CPATH=/opt/homebrew/anaconda3/envs/pytorch/lib/python3.8/site-packages/numpy/core/include/:$CPATH
```
Replace the pathway where the `numpy/arrayobject.h` is in.

**Comment by a-r-j** [comment]
Thanks for sharing your fix!
